Added/fixed filters, added bicleaner-hardrules as a filter
hplt-project/OpusCleaner pull request #51
Opened 2022-11-22 10:38 UTC by TudorMN

- Added filters from OpusFilter
- Modified empty-train filters
- Fixed some minor issues in the previous git pull
- Added bicleaner-hardrules as an individual modifiable filter in `bicleaner_all_hardrules`
- Deleted `no_porn` filter, recommend using the one from the newly added bicleaner-hardrules filter

2022-12-05 11:44 UTC, jelmervdl commented
@TudorMN @ZJaume I'm a bit confused as what happened to bicleaner_hardrules. I was under the impression that we would add them as separate filters, but implement all of them by just calling the existing python library.

Its a small difference, but quite a difference in the user experience. By splitting up the filter into separate filters you'd be able to search for them, and the interface will be easier to understand.

Implementation wise you can do something similar to what I did in #47 where all the json files call the same python script to execute the actual filter.

2022-12-05 11:45 UTC, jelmervdl commented on filters/avg_word_length.py
> +    parser.add_argument("--min-avg-length", default=20, type=int)
Nitpick but default should be same as in the json: `default=2`

2022-12-05 14:06 UTC, jelmervdl requested changes

2022-12-05 14:06 UTC, jelmervdl commented on filters/no_porn.py
> +        trg_porn_pass = porn_tokenizer_lang2.tokenize(trg.lower())
This seems to tokenize. But it is missing the porn classification?

2023-11-23 18:07 UTC, XapaJIaMnu commented
We already have bicleaner-hardrules. Are there things here that are waiting to be merged?

2024-04-16 14:26 UTC, closed without merging